---
title: Perfectly something
timezone: Europe/Paris
collections:
  categories:
    title: Categories
    output: true
  posts:
    title: Posts
    output: true
  "-blog-tags-":
    title: Tags
    output: true
  uploads:
    title: Uploads
    output: true
future: true
email: 
baseurl: 
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 
description: Blog test
url: 
twitter_username: 
default_img: 
name: 
profile_img: 
profile: 
social:
  github: 
  twitter: 
  instagram: 
  pinterest: 
include:
- _categories
- _tags
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
gems:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
